const sb=window.ipmoSupabase;
const login=document.querySelector('#loginPanel'), editor=document.querySelector('#editorPanel'), statusEl=document.querySelector('#adminStatus');
const form=document.querySelector('#postForm'), list=document.querySelector('#postsList');
let editingId=null, categories=[];
function msg(t,ok=true){statusEl.textContent=t;statusEl.className=ok?'admin-status ok':'admin-status err';}
function slugify(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');}
async function checkAccess(){
 const {data:{session}}=await sb.auth.getSession(); if(!session){login.hidden=false;editor.hidden=true;return;}
 const {data:profile}=await sb.from('profiles').select('role,full_name').eq('id',session.user.id).maybeSingle();
 if(!profile||!['admin','editor'].includes(profile.role)){await sb.auth.signOut();login.hidden=false;editor.hidden=true;msg('Sua conta ainda não possui permissão editorial.',false);return;}
 login.hidden=true;editor.hidden=false;document.querySelector('#whoami').textContent=profile.full_name||session.user.email; await loadCategories();await loadPosts();
}
document.querySelector('#showSignupBtn').addEventListener('click',()=>{const f=document.querySelector('#signupForm');f.hidden=!f.hidden;});
document.querySelector('#signupForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(fd.get('password')!==fd.get('password2'))return msg('As senhas não coincidem.',false);const {data,error}=await sb.auth.signUp({email:String(fd.get('email')).trim().toLowerCase(),password:fd.get('password'),options:{data:{full_name:fd.get('full_name')},emailRedirectTo:`${window.location.origin}/admin.html`}});if(error)return msg(error.message,false);if(data.session){msg('Acesso criado. Entrando no Painel Editorial…');return checkAccess();}msg('Cadastro criado. Verifique seu e-mail para confirmar o acesso e depois entre no painel.');e.currentTarget.reset();});
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);const {error}=await sb.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return msg(error.message,false);msg('Login realizado.');checkAccess();});
document.querySelector('#logoutBtn').addEventListener('click',async()=>{await sb.auth.signOut();location.reload();});
async function loadCategories(){const {data}=await sb.from('categories').select('id,name,slug').order('name');categories=data||[];document.querySelector('#category').innerHTML=categories.map(c=>`<option value="${c.id}">${c.name}</option>`).join('');}
async function loadPosts(){const {data,error}=await sb.from('posts').select('id,title,status,is_featured,published_at,created_at,categories(name)').order('created_at',{ascending:false});if(error)return msg(error.message,false);list.innerHTML=(data||[]).map(p=>`<div class="post-row"><div><strong>${p.title}</strong><small>${p.categories?.name||''} · ${p.status}</small></div><div><button data-edit="${p.id}">Editar</button><button data-delete="${p.id}" class="danger">Excluir</button></div></div>`).join('')||'<p>Nenhuma notícia cadastrada.</p>'; list.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editPost(b.dataset.edit));list.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete));}
async function editPost(id){const {data:p}=await sb.from('posts').select('*').eq('id',id).single();editingId=id;document.querySelector('#title').value=p.title;document.querySelector('#slug').value=p.slug;document.querySelector('#excerpt').value=p.excerpt||'';document.querySelector('#content').value=p.content||'';document.querySelector('#category').value=p.category_id||'';document.querySelector('#status').value=p.status;document.querySelector('#featured').checked=p.is_featured;document.querySelector('#currentImage').value=p.cover_image_url||'';document.querySelector('#formTitle').textContent='Editar notícia';window.scrollTo({top:0,behavior:'smooth'});}
async function deletePost(id){if(!confirm('Excluir esta notícia?'))return;const {error}=await sb.from('posts').delete().eq('id',id);if(error)return msg(error.message,false);msg('Notícia excluída.');loadPosts();}
document.querySelector('#title').addEventListener('input',e=>{if(!editingId)document.querySelector('#slug').value=slugify(e.target.value);});
document.querySelector('#resetBtn').addEventListener('click',()=>{editingId=null;form.reset();document.querySelector('#formTitle').textContent='Nova notícia';});
form.addEventListener('submit',async e=>{e.preventDefault();const fd=new FormData(form);let imageUrl=document.querySelector('#currentImage').value||null;const file=fd.get('image');if(file&&file.size){const path=`${Date.now()}-${slugify(file.name)}`;const {error:upErr}=await sb.storage.from('news-images').upload(path,file,{upsert:false});if(upErr)return msg(upErr.message,false);const {data:u}=sb.storage.from('news-images').getPublicUrl(path);imageUrl=u.publicUrl;}
 const {data:{user}}=await sb.auth.getUser();const status=fd.get('status');const payload={title:fd.get('title'),slug:fd.get('slug'),excerpt:fd.get('excerpt'),content:fd.get('content'),category_id:fd.get('category')||null,cover_image_url:imageUrl,status,is_featured:fd.get('featured')==='on',author_id:user.id,published_at:status==='published'?new Date().toISOString():null};
 const q=editingId?sb.from('posts').update(payload).eq('id',editingId):sb.from('posts').insert(payload);const {error}=await q;if(error)return msg(error.message,false);msg(editingId?'Notícia atualizada.':'Notícia salva.');editingId=null;form.reset();document.querySelector('#formTitle').textContent='Nova notícia';loadPosts();});
checkAccess();
